[build]
  publish = "public"
  functions = "api/netlify/functions"
  command = "cd api/netlify && npm install"

[template.environment]
  RECURLY_API_KEY = "Your Recurly PRIVATE key"
  RECURLY_PUBLIC_KEY = "Your Recurly PUBLIC key"
  SUCCESS_URL = "Redirect URL for new suscription success"
  ERROR_URL = "Redirect URL for new subscription error"

[[redirects]]
  from = "/api/subscriptions/new"
  to = "/.netlify/functions/new-subscription"
  status = 200

[[redirects]]
  from = "/api/accounts/new"
  to = "/.netlify/functions/new-account"
  status = 200

[[redirects]]
  from = "/api/accounts/:account"
  to = "/.netlify/functions/update-account/:account"
  status = 200
